# Generated by Django 5.1.2 on 2026-04-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GearRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('partner_url', models.URLField()),
                ('image_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
