# Generated by Django 5.1.2 on 2026-04-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('latin_name', models.CharField(blank=True, max_length=120)),
                ('min_size_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('daily_limit', models.CharField(blank=True, max_length=120)),
                ('methods', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
