# Generated by Django 5.1.2 on 2026-04-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishingRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('area', models.CharField(blank=True, max_length=180)),
                ('season', models.CharField(blank=True, max_length=180)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
